### ISSUE TITLE
Missing notification on Android 13

### ISSUE THREAD

**Issue by ewoerner** [bannergress/banner-overlay#16]
Android 13 requires explicit permission.

**Comment by elkuku** [comment]
Is the notification responsible for closing the app?
If so, I was just about to open a new issue...


BTW I really love the idea of this app. I believe its the best idea since someone thought of combining missions into banners ;)

Works perfect on Android < 13

One small feature request: Could you add an option (somewhere) to change the color?... (I'd prefer green of course :wink:)

**Comment by ewoerner** [comment]
Fixed in #29
